// Migrated from frontend/src/context/CityContext.jsx
// lat/lng added (approximate city-center coordinates) so the Month 3 weather
// feature has real coordinates to query instead of the mapX/mapY SVG percentages.
//
// NOTE: "Kerala" was stored as a state, not a single city — coordinates below
// point to Kochi as a representative location. Before wiring up weather,
// consider splitting this into specific cities (Kochi, Munnar, Alleppey) so
// forecasts are actually meaningful.

export const citiesData = [
  {
    name: "Jaipur",
    slug: "jaipur",
    state: "Rajasthan",
    region: "North",
    tagline: "The Pink City of India",
    subtitle: "Where every stone whispers stories of maharajas and moonlight",
    about:
      "Step into a city draped in terracotta hues, where forts rise from golden hills, bazaars hum with silk and spice, and every sunset turns the sky into a masterpiece. Jaipur doesn't just welcome you — it enchants you.",
    badge: "The Pink City",
    bestSeason: "Oct – Mar",
    rating: 4.8,
    budget: "₹5k – ₹20k",
    image: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=1200&q=80",
    ecoOptions: ["🛺 E-Rickshaw", "🐪 Camel Ride", "🚶 Heritage Walk"],
    mapX: 38,
    mapY: 35,
    lat: 26.9124,
    lng: 75.7873,
    isEnriched: true,
    stats: [
      { value: "300+", label: "Years of History" },
      { value: "4.8★", label: "Traveller Rating" },
      { value: "3", label: "UNESCO Sites" },
      { value: "12M+", label: "Annual Visitors" },
    ],
    attractions: [
      {
        name: "Amber Fort",
        desc: "A majestic palace complex perched atop the Aravalli hills, with mirror halls, elephant corridors, and sweeping lake views that leave you breathless.",
        image: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=800&q=80",
        tags: [{ label: "UNESCO", color: "#FF6B1A" }, { label: "Must Visit", color: "#6B1A1A" }],
        rating: "4.9", reviews: "48K", hours: "8AM – 5:30PM",
      },
      {
        name: "Hawa Mahal",
        desc: "The Palace of Winds — a five-storey honeycomb of 953 carved windows, built so royal ladies could observe street festivities while remaining unseen.",
        image: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=800&q=80",
        tags: [{ label: "Iconic", color: "#FF6B1A" }, { label: "UNESCO", color: "#FF6B1A" }],
        rating: "4.8", reviews: "62K", hours: "9AM – 4:30PM",
      },
      {
        name: "City Palace",
        desc: "A grand palace complex at the heart of Jaipur's walled city, home to royal art galleries, silver urns, and opulent courtyards still used by the royal family.",
        image: "https://images.unsplash.com/photo-1661924326425-c14a6426d989?w=800&q=80",
        tags: [{ label: "Royal", color: "#6B1A1A" }, { label: "Heritage", color: "#b37a00" }],
        rating: "4.7", reviews: "35K", hours: "9:30AM – 5PM",
      },
      {
        name: "Jantar Mantar",
        desc: "The world's largest stone astronomical observatory, built in 1724. Its giant instruments measure time, predict eclipses, and track stars with startling accuracy.",
        image: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=800&q=80",
        tags: [{ label: "UNESCO", color: "#FF6B1A" }, { label: "Science", color: "#2e7d32" }],
        rating: "4.6", reviews: "28K", hours: "9AM – 4:30PM",
      },
      {
        name: "Nahargarh Fort",
        desc: 'Perched on the rocky Aravalli ridge, this "Tiger Fort" offers the most dramatic panoramic view of Jaipur — especially at twilight when the city glows amber.',
        image: "https://images.unsplash.com/photo-1653495484044-479eeabe94ab?w=800&q=80",
        tags: [{ label: "Sunset Spot", color: "#e05a10" }, { label: "Fort", color: "#6B1A1A" }],
        rating: "4.5", reviews: "22K", hours: "10AM – 5:30PM",
      },
      {
        name: "Johari Bazaar",
        desc: "Jaipur's legendary jewellery market, glittering with kundan, meenakari, and precious gemstones. Also home to vibrant textile stalls and the city's finest silver.",
        image: "https://images.unsplash.com/photo-1606837731918-f006ef0ef3da?w=800&q=80",
        tags: [{ label: "Shopping", color: "#b37a00" }, { label: "Cultural", color: "#5c3d8f" }],
        rating: "4.6", reviews: "19K", hours: "10AM – 8PM",
      },
    ],
    foodRecommendations: [
      {
        name: "Laxmi Misthan Bhandar (LMB)",
        desc: "A Jaipur institution since 1954 — their sweets and Rajasthani thali are legendary.",
        type: "Heritage Restaurant",
        image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=300&fit=crop",
      },
      {
        name: "Suvarna Mahal, Rambagh Palace",
        desc: "Dine like royalty in a gilded ballroom with the finest Rajasthani and Mughal cuisine.",
        type: "Luxury / Fine Dining",
        image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop",
      },
      {
        name: "Peacock Rooftop Restaurant",
        desc: "Rooftop dining with views of Hawa Mahal — perfect at sunset with a cold lassi.",
        type: "Views + Great Food",
        image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=400&h=300&fit=crop",
      },
      {
        name: "Rawat Mishthan Bhandar",
        desc: "The birthplace of Jaipur's famous Pyaaz Kachori. No visit is complete without stopping here.",
        type: "Street Food Icon",
        image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400&h=300&fit=crop",
      },
    ],
    activities: [
      {
        name: "Elephant Ride at Amber Fort",
        desc: "Ascend to Amber Fort on the back of a majestic painted elephant — a royal arrival befitting the palace you're about to enter.",
        icon: "🐘",
        time: "Morning Only",
        image: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=600&h=400&fit=crop",
      },
      {
        name: "Shopping in Johari Bazaar",
        desc: "Hunt for blue pottery, kundan jewellery, block-printed textiles, and handcrafted leather shoes in Jaipur's bustling walled-city markets.",
        icon: "💍",
        time: "Evening Best",
        image: "https://images.unsplash.com/photo-1606837731918-f006ef0ef3da?w=600&h=400&fit=crop",
      },
      {
        name: "Sunset at Nahargarh Fort",
        desc: "Watch the Pink City blush deeper as the sun melts into the Aravalli ridgeline — one of India's most dramatic and romantic sunsets.",
        icon: "🌅",
        time: "5 PM – 7 PM",
        image: "https://images.unsplash.com/photo-1653495484044-479eeabe94ab?w=600&h=400&fit=crop",
      },
      {
        name: "Cultural Shows & Folk Dance",
        desc: "Experience Kalbelia snake-charmer dances, puppet shows, and Ghoomar performances at Chokhi Dhani — a village turned cultural theme park.",
        icon: "💃",
        time: "Evening Show",
        image: "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=600&h=400&fit=crop",
      },
    ],
    hiddenGems: [
      {
        name: "Panna Meena Ka Kund",
        desc: "A mesmerising 16th-century stepwell near Amber Fort with symmetrical staircases forming perfect geometric patterns. Peaceful, photogenic, and almost always uncrowded.",
        icon: "🪜",
        location: "Amer",
        image: "https://images.unsplash.com/photo-1630261000949-b4a3c3571af4?w=600&h=400&fit=crop",
      },
      {
        name: "Jawahar Circle Garden",
        desc: "The largest circular park in Asia, this gorgeous garden dazzles at evening with illuminated fountains and manicured flower beds. Perfect for a quiet evening stroll.",
        icon: "🌸",
        location: "Malviya Nagar",
        image: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=600&h=400&fit=crop",
      },
      {
        name: "Kanak Vrindavan Garden",
        desc: "Nestled beside the Jal Mahal lake, this serene 18th-century garden with its ornate temples and peacock-filled lawns is overlooked by nearly every tourist guide.",
        icon: "🌺",
        location: "Nahargarh Road",
        image: "https://images.unsplash.com/photo-1661924326425-c14a6426d989?w=600&h=400&fit=crop",
      },
      {
        name: "Chandlai Lake",
        desc: "A birder's paradise just 25km from Jaipur — winter months bring flamingos, cranes, and migratory ducks in stunning numbers. Bring binoculars and your silence.",
        icon: "🦢",
        location: "25km from City",
        image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&h=400&fit=crop",
      },
    ],
    nearby: [
      {
        name: "Ajmer",
        emoji: "🕌",
        desc: "Home to the revered Dargah of Sufi saint Moinuddin Chishti, Ajmer radiates a profound spiritual calm. Visit during Urs festival for an otherworldly experience.",
        distance: "135 km · ~2.5 hrs by road",
        image: "https://images.unsplash.com/photo-1666175146759-ce6a39f991ae?w=600&h=400&fit=crop",
      },
      {
        name: "Pushkar",
        emoji: "🐪",
        desc: "A sacred lake town with 52 bathing ghats and over 400 temples. November's Pushkar Camel Fair is one of the world's most surreal spectacles.",
        distance: "145 km · ~3 hrs by road",
        image: "https://images.unsplash.com/photo-1715168931029-2949161ee406?w=600&h=400&fit=crop",
      },
      {
        name: "Ranthambore",
        emoji: "🐯",
        desc: "India's most famed tiger reserve, set against ancient fort ruins. A morning safari here, watching a Bengal tiger stalk through tall grass, is a defining life experience.",
        distance: "180 km · ~3.5 hrs by road",
        image: "https://images.unsplash.com/photo-1725990076174-a3448eb86e76?w=600&h=400&fit=crop",
      },
    ],
    months: [
      { m: "Jan", range: "8°– 22°C", label: "Cold Nights", type: "warn" },
      { m: "Feb", range: "12°– 25°C", label: "Great!", type: "good" },
      { m: "Mar", range: "18°– 32°C", label: "Best", type: "best" },
      { m: "Apr", range: "25°– 38°C", label: "Warm", type: "warn" },
      { m: "May", range: "30°– 44°C", label: "Very Hot", type: "bad" },
      { m: "Jun", range: "28°– 42°C", label: "Monsoon", type: "bad" },
      { m: "Jul", range: "25°– 37°C", label: "Heavy Rain", type: "bad" },
      { m: "Aug", range: "24°– 34°C", label: "Clearing", type: "warn" },
      { m: "Sep", range: "22°– 33°C", label: "Good", type: "good" },
      { m: "Oct", range: "18°– 32°C", label: "Best", type: "best" },
      { m: "Nov", range: "12°– 26°C", label: "Ideal", type: "best" },
      { m: "Dec", range: "8°– 22°C", label: "Chilly", type: "warn" },
    ],
    tips: [
      { icon: "😎", title: "Beat the Heat", desc: "Visit April–June before 10AM and after 5PM. Carry electrolytes and wear light cotton." },
      { icon: "🧥", title: "Winter Nights", desc: "December–January evenings drop to 5–8°C. Pack a warm jacket for open-air heritage dinners." },
      { icon: "🤝", title: "Bargain Wisely", desc: "Haggling is expected at bazaars. Start at 50% of the quoted price. Always smile — it's part of the ritual." },
      { icon: "🌸", title: "Festival Timing", desc: "Visit during Diwali (Oct–Nov) or Holi (Mar) for a transformative cultural experience — but book 3 months ahead." },
    ],
    checklist: {
      Summer: ["High-SPF sunscreen (SPF 50+)", "2-litre reusable water bottle", "Light cotton or linen clothing", "UV-protective sunglasses", "Wide-brimmed hat or scarf", "ORS sachets / electrolyte tablets", "Cooling face mist spray", "Portable fan or mini cooler"],
      Winter: ["Warm jacket or shawl", "Thermal innerwear for evenings", "Comfortable walking shoes", "Lip balm & moisturiser", "Scarf for cold mornings", "Hand warmers"],
      Essentials: ["Aadhaar / passport copy", "Travel insurance docs", "Offline maps (Google Maps)", "Cash in small denominations", "Reusable bag for shopping", "Basic first-aid kit", "Power bank", "Camera with extra memory"],
    },
  },
  {
    name: "Varanasi",
    slug: "varanasi",
    state: "Uttar Pradesh",
    region: "North",
    tagline: "City of Light & Spirituality",
    bestSeason: "Nov – Mar",
    rating: 4.7,
    budget: "₹4k – ₹15k",
    image: "https://images.pexels.com/photos/36565405/pexels-photo-36565405.jpeg",
    ecoOptions: ["🛶 Ganga Boat", "🚶 Ghat Walk", "🛺 E-Rickshaw"],
    mapX: 52,
    mapY: 33,
    lat: 25.3176,
    lng: 82.9739,
  },
  {
    name: "Agra",
    slug: "agra",
    state: "Uttar Pradesh",
    region: "North",
    tagline: "Home of the Taj Mahal",
    bestSeason: "Oct – Mar",
    rating: 4.6,
    budget: "₹5k – ₹18k",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    ecoOptions: ["🛺 E-Rickshaw", "🚲 Cycle Tour", "🚶 Walking"],
    mapX: 46,
    mapY: 32,
    lat: 27.1767,
    lng: 78.0081,
  },
  {
    name: "Goa",
    slug: "goa",
    state: "Goa",
    region: "West",
    tagline: "Sun, Sand & Soul",
    bestSeason: "Nov – Feb",
    rating: 4.9,
    budget: "₹6k – ₹25k",
    image: "https://images.pexels.com/photos/28368721/pexels-photo-28368721.jpeg",
    ecoOptions: ["🚲 Cycle Beaches", "🛺 E-Rickshaw", "🚶 Spice Walk"],
    mapX: 28,
    mapY: 58,
    lat: 15.2993,
    lng: 74.1240,
  },
  {
    name: "Udaipur",
    slug: "udaipur",
    state: "Rajasthan",
    region: "West",
    tagline: "City of Lakes & Palaces",
    bestSeason: "Sep – Mar",
    rating: 4.8,
    budget: "₹6k – ₹22k",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
    ecoOptions: ["🛶 Lake Boat", "🚶 Old City Walk", "🛺 E-Rickshaw"],
    mapX: 32,
    mapY: 40,
    lat: 24.5854,
    lng: 73.7125,
  },
  {
    name: "Mumbai",
    slug: "mumbai",
    state: "Maharashtra",
    region: "West",
    tagline: "City of Dreams & Energy",
    bestSeason: "Nov – Feb",
    rating: 4.5,
    budget: "₹8k – ₹30k",
    image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=600&q=80",
    ecoOptions: ["🚇 Local Train", "🚶 Marine Drive", "🚌 BEST Bus"],
    mapX: 27,
    mapY: 53,
    lat: 19.0760,
    lng: 72.8777,
  },
  {
    name: "Kerala",
    slug: "kerala",
    state: "Kerala",
    region: "South",
    tagline: "God's Own Country",
    bestSeason: "Sep – Mar",
    rating: 4.9,
    budget: "₹7k – ₹28k",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    ecoOptions: ["🚤 Houseboat", "🚶 Tea Walk", "🚲 Village Cycle"],
    mapX: 32,
    mapY: 78,
    lat: 9.9312,
    lng: 76.2673,
  },
  {
    name: "Bengaluru",
    slug: "bengaluru",
    state: "Karnataka",
    region: "South",
    tagline: "Garden City of India",
    bestSeason: "Oct – Feb",
    rating: 4.4,
    budget: "₹6k – ₹20k",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=600&q=80",
    ecoOptions: ["🚇 Metro", "🚲 Cycling", "🚌 BMTC Bus"],
    mapX: 36,
    mapY: 72,
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    name: "Kolkata",
    slug: "kolkata",
    state: "West Bengal",
    region: "East",
    tagline: "City of Joy & Culture",
    bestSeason: "Oct – Mar",
    rating: 4.6,
    budget: "₹4k – ₹15k",
    image: "https://i.pinimg.com/736x/73/76/34/737634298fa3cf9c29164812ac95ff79.jpg",
    ecoOptions: ["🚃 Tram Ride", "🚶 Heritage Walk", "🛺 Rickshaw"],
    mapX: 68,
    mapY: 42,
    lat: 22.5726,
    lng: 88.3639,
  },
  {
    name: "Darjeeling",
    slug: "darjeeling",
    state: "West Bengal",
    region: "East",
    tagline: "Queen of the Hills",
    bestSeason: "Mar – May, Sep – Nov",
    rating: 4.7,
    budget: "₹5k – ₹18k",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    ecoOptions: ["🚂 Toy Train", "🚶 Tea Garden", "🐎 Horse Ride"],
    mapX: 72,
    mapY: 32,
    lat: 27.0410,
    lng: 88.2663,
  },
  {
    name: "Rishikesh",
    slug: "rishikesh",
    state: "Uttarakhand",
    region: "North",
    tagline: "Adventure & Yoga Capital",
    bestSeason: "Feb – May, Sep – Nov",
    rating: 4.7,
    budget: "₹4k – ₹15k",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    ecoOptions: ["🚶 Ganga Walk", "🚲 Cycling", "🛶 River Rafting"],
    mapX: 42,
    mapY: 24,
    lat: 30.0869,
    lng: 78.2676,
  },
  {
    name: "Hampi",
    slug: "hampi",
    state: "Karnataka",
    region: "South",
    tagline: "Ruins of a Forgotten Empire",
    bestSeason: "Oct – Feb",
    rating: 4.8,
    budget: "₹3k – ₹12k",
    image: "https://images.pexels.com/photos/14721497/pexels-photo-14721497.jpeg",
    ecoOptions: ["🚲 Cycling Ruins", "🛶 Coracle Boat", "🚶 Temple Walk"],
    mapX: 36,
    mapY: 65,
    lat: 15.3350,
    lng: 76.4600,
  },
];