// Migrated from frontend/src/context/CityContext.jsx
// lat/lng added (approximate city-center coordinates) so the Month 3 weather
// feature has real coordinates to query instead of the mapX/mapY SVG percentages.
//
// NOTE: "Kerala" was stored as a state, not a single city — coordinates below
// point to Kochi as a representative location. Before wiring up weather,
// consider splitting this into specific cities (Kochi, Munnar, Alleppey) so
// forecasts are actually meaningful.

export const citiesData = [
  {
    name: "Jaipur",
    slug: "jaipur",
    state: "Rajasthan",
    region: "North",
    tagline: "The Pink City of India",
    bestSeason: "Oct – Mar",
    rating: 4.8,
    budget: "₹5k – ₹20k",
    image: "https://images.pexels.com/photos/36418716/pexels-photo-36418716.jpeg",
    ecoOptions: ["🛺 E-Rickshaw", "🐪 Camel Ride", "🚶 Heritage Walk"],
    mapX: 38,
    mapY: 35,
    lat: 26.9124,
    lng: 75.7873,
  },
  {
    name: "Varanasi",
    slug: "varanasi",
    state: "Uttar Pradesh",
    region: "North",
    tagline: "City of Light & Spirituality",
    bestSeason: "Nov – Mar",
    rating: 4.7,
    budget: "₹4k – ₹15k",
    image: "https://images.pexels.com/photos/36565405/pexels-photo-36565405.jpeg",
    ecoOptions: ["🛶 Ganga Boat", "🚶 Ghat Walk", "🛺 E-Rickshaw"],
    mapX: 52,
    mapY: 33,
    lat: 25.3176,
    lng: 82.9739,
  },
  {
    name: "Agra",
    slug: "agra",
    state: "Uttar Pradesh",
    region: "North",
    tagline: "Home of the Taj Mahal",
    bestSeason: "Oct – Mar",
    rating: 4.6,
    budget: "₹5k – ₹18k",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    ecoOptions: ["🛺 E-Rickshaw", "🚲 Cycle Tour", "🚶 Walking"],
    mapX: 46,
    mapY: 32,
    lat: 27.1767,
    lng: 78.0081,
  },
  {
    name: "Goa",
    slug: "goa",
    state: "Goa",
    region: "West",
    tagline: "Sun, Sand & Soul",
    bestSeason: "Nov – Feb",
    rating: 4.9,
    budget: "₹6k – ₹25k",
    image: "https://images.pexels.com/photos/28368721/pexels-photo-28368721.jpeg",
    ecoOptions: ["🚲 Cycle Beaches", "🛺 E-Rickshaw", "🚶 Spice Walk"],
    mapX: 28,
    mapY: 58,
    lat: 15.2993,
    lng: 74.1240,
  },
  {
    name: "Udaipur",
    slug: "udaipur",
    state: "Rajasthan",
    region: "West",
    tagline: "City of Lakes & Palaces",
    bestSeason: "Sep – Mar",
    rating: 4.8,
    budget: "₹6k – ₹22k",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
    ecoOptions: ["🛶 Lake Boat", "🚶 Old City Walk", "🛺 E-Rickshaw"],
    mapX: 32,
    mapY: 40,
    lat: 24.5854,
    lng: 73.7125,
  },
  {
    name: "Mumbai",
    slug: "mumbai",
    state: "Maharashtra",
    region: "West",
    tagline: "City of Dreams & Energy",
    bestSeason: "Nov – Feb",
    rating: 4.5,
    budget: "₹8k – ₹30k",
    image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=600&q=80",
    ecoOptions: ["🚇 Local Train", "🚶 Marine Drive", "🚌 BEST Bus"],
    mapX: 27,
    mapY: 53,
    lat: 19.0760,
    lng: 72.8777,
  },
  {
    name: "Kerala",
    slug: "kerala",
    state: "Kerala",
    region: "South",
    tagline: "God's Own Country",
    bestSeason: "Sep – Mar",
    rating: 4.9,
    budget: "₹7k – ₹28k",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    ecoOptions: ["🚤 Houseboat", "🚶 Tea Walk", "🚲 Village Cycle"],
    mapX: 32,
    mapY: 78,
    lat: 9.9312,
    lng: 76.2673,
  },
  {
    name: "Bengaluru",
    slug: "bengaluru",
    state: "Karnataka",
    region: "South",
    tagline: "Garden City of India",
    bestSeason: "Oct – Feb",
    rating: 4.4,
    budget: "₹6k – ₹20k",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=600&q=80",
    ecoOptions: ["🚇 Metro", "🚲 Cycling", "🚌 BMTC Bus"],
    mapX: 36,
    mapY: 72,
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    name: "Kolkata",
    slug: "kolkata",
    state: "West Bengal",
    region: "East",
    tagline: "City of Joy & Culture",
    bestSeason: "Oct – Mar",
    rating: 4.6,
    budget: "₹4k – ₹15k",
    image: "https://i.pinimg.com/736x/73/76/34/737634298fa3cf9c29164812ac95ff79.jpg",
    ecoOptions: ["🚃 Tram Ride", "🚶 Heritage Walk", "🛺 Rickshaw"],
    mapX: 68,
    mapY: 42,
    lat: 22.5726,
    lng: 88.3639,
  },
  {
    name: "Darjeeling",
    slug: "darjeeling",
    state: "West Bengal",
    region: "East",
    tagline: "Queen of the Hills",
    bestSeason: "Mar – May, Sep – Nov",
    rating: 4.7,
    budget: "₹5k – ₹18k",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    ecoOptions: ["🚂 Toy Train", "🚶 Tea Garden", "🐎 Horse Ride"],
    mapX: 72,
    mapY: 32,
    lat: 27.0410,
    lng: 88.2663,
  },
  {
    name: "Rishikesh",
    slug: "rishikesh",
    state: "Uttarakhand",
    region: "North",
    tagline: "Adventure & Yoga Capital",
    bestSeason: "Feb – May, Sep – Nov",
    rating: 4.7,
    budget: "₹4k – ₹15k",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    ecoOptions: ["🚶 Ganga Walk", "🚲 Cycling", "🛶 River Rafting"],
    mapX: 42,
    mapY: 24,
    lat: 30.0869,
    lng: 78.2676,
  },
  {
    name: "Hampi",
    slug: "hampi",
    state: "Karnataka",
    region: "South",
    tagline: "Ruins of a Forgotten Empire",
    bestSeason: "Oct – Feb",
    rating: 4.8,
    budget: "₹3k – ₹12k",
    image: "https://images.pexels.com/photos/14721497/pexels-photo-14721497.jpeg",
    ecoOptions: ["🚲 Cycling Ruins", "🛶 Coracle Boat", "🚶 Temple Walk"],
    mapX: 36,
    mapY: 65,
    lat: 15.3350,
    lng: 76.4600,
  },
];